import type { Metadata } from 'next';
import './globals.css';
import TTHovesFont from '@/fonts/fontsSetup';

// needs to be remade
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={TTHovesFont.variable}>
      <body className="font-tthoves">{children}</body>
    </html>
  );
}
