import type { Metadata } from 'next';
import './globals.css';
import TTHovesFont from '@/fonts/fontsSetup';

import LayoutContainer from '@/ui/LayoutContainer/LayoutContainer';

// needs to be remade
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={TTHovesFont.variable}>
      <body>
        <LayoutContainer>
          {children}
        </LayoutContainer>
      </body>
    </html>
  );
}
